// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"quick-go/app/http/controllers"
	"quick-go/app/repo"
	"quick-go/app/service"
	"quick-go/bootstrap"
	"quick-go/global"
	"quick-go/routers"
)

// Injectors from wire.go:

func InitServer() (*bootstrap.Server, func(), error) {
	engine := bootstrap.NewGinEngine()
	data, cleanup, err := global.NewData()
	if err != nil {
		return nil, nil, err
	}
	iStockRepo := repo.NewMysqlStockRepository(data)
	iStockService := service.NewStockService(iStockRepo)
	stockController := controllers.NewStockController(iStockService)
	router := routers.NewRouter(stockController)
	server := bootstrap.NewServer(engine, router)
	return server, func() {
		cleanup()
	}, nil
}
