// 指定 proto 的版本信息

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.0
// source: app/rpc/hello.proto

// 指定所在包的包名

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义请求消息体
type GetBrandInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BrandId int64 `protobuf:"varint,1,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
}

func (x *GetBrandInfoReq) Reset() {
	*x = GetBrandInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_rpc_hello_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBrandInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrandInfoReq) ProtoMessage() {}

func (x *GetBrandInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_hello_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrandInfoReq.ProtoReflect.Descriptor instead.
func (*GetBrandInfoReq) Descriptor() ([]byte, []int) {
	return file_app_rpc_hello_proto_rawDescGZIP(), []int{0}
}

func (x *GetBrandInfoReq) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

// 定义响应消息体
type GetBrandInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BrandId      int64   `protobuf:"varint,1,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	BrandName    string  `protobuf:"bytes,2,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	BrandAdvList []int64 `protobuf:"varint,3,rep,packed,name=brand_adv_list,json=brandAdvList,proto3" json:"brand_adv_list,omitempty"`
}

func (x *GetBrandInfoRsp) Reset() {
	*x = GetBrandInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_rpc_hello_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBrandInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrandInfoRsp) ProtoMessage() {}

func (x *GetBrandInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_app_rpc_hello_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrandInfoRsp.ProtoReflect.Descriptor instead.
func (*GetBrandInfoRsp) Descriptor() ([]byte, []int) {
	return file_app_rpc_hello_proto_rawDescGZIP(), []int{1}
}

func (x *GetBrandInfoRsp) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *GetBrandInfoRsp) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *GetBrandInfoRsp) GetBrandAdvList() []int64 {
	if x != nil {
		return x.BrandAdvList
	}
	return nil
}

var File_app_rpc_hello_proto protoreflect.FileDescriptor

var file_app_rpc_hello_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x70, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x2c, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a,
	0x08, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x22, 0x71, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42,
	0x72, 0x61, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x62,
	0x72, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62,
	0x72, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x72, 0x61, 0x6e,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x61,
	0x64, 0x76, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0c, 0x62,
	0x72, 0x61, 0x6e, 0x64, 0x41, 0x64, 0x76, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x4a, 0x0a, 0x0c, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x1a, 0x14, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x72, 0x61, 0x6e, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x61, 0x70, 0x70, 0x2f,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_rpc_hello_proto_rawDescOnce sync.Once
	file_app_rpc_hello_proto_rawDescData = file_app_rpc_hello_proto_rawDesc
)

func file_app_rpc_hello_proto_rawDescGZIP() []byte {
	file_app_rpc_hello_proto_rawDescOnce.Do(func() {
		file_app_rpc_hello_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_rpc_hello_proto_rawDescData)
	})
	return file_app_rpc_hello_proto_rawDescData
}

var file_app_rpc_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_rpc_hello_proto_goTypes = []interface{}{
	(*GetBrandInfoReq)(nil), // 0: rpc.GetBrandInfoReq
	(*GetBrandInfoRsp)(nil), // 1: rpc.GetBrandInfoRsp
}
var file_app_rpc_hello_proto_depIdxs = []int32{
	0, // 0: rpc.HelloService.GetBrandInfo:input_type -> rpc.GetBrandInfoReq
	1, // 1: rpc.HelloService.GetBrandInfo:output_type -> rpc.GetBrandInfoRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_rpc_hello_proto_init() }
func file_app_rpc_hello_proto_init() {
	if File_app_rpc_hello_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_rpc_hello_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBrandInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_rpc_hello_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBrandInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_rpc_hello_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_rpc_hello_proto_goTypes,
		DependencyIndexes: file_app_rpc_hello_proto_depIdxs,
		MessageInfos:      file_app_rpc_hello_proto_msgTypes,
	}.Build()
	File_app_rpc_hello_proto = out.File
	file_app_rpc_hello_proto_rawDesc = nil
	file_app_rpc_hello_proto_goTypes = nil
	file_app_rpc_hello_proto_depIdxs = nil
}
