dbLocal:
  host: 192.168.80.1
  user: root
  port: 3328
  pwd: root

redisLocal:
  host: 192.168.80.1
  password:
  port: 6390

localKafka:
  addr: 192.168.80.1:9092
  topic: test

# 开发的端口
port: 8080
# 日志记录的目录
logPath: ./storage/logs/


# http port
httpPort: 8080
grpcPort: 8081