dbLocal:
  host: localhost
  user: root
  port: 3328
  pwd: root

redisLocal:
  host: localhost
  password:
  port: 6390

localKafka:
  addr: localhost:9092
  topic: test

# 开发的端口
port: 8080

# 日志记录的目录
logPath: ./storage/logs/
